// Mock "데이터베이스".
//
// 이 프로젝트가 검증하려는 것은 "침수 위험을 판단하는 로직"이지, 매물 인벤토리 구축이
// 아닙니다. 매물명·가격·중개사·사진 같은 정보는 데모용 예시이며, 실제 서비스라면 이
// 자리에 직방·네이버부동산·당근부동산처럼 이미 매물 데이터를 가진 플랫폼의 DB가 들어오고
// (이 로직을 SaaS/API로 공급하는 그림), 각 매물의 좌표만 넘겨받아 아래 계산을 그대로
// 재사용하게 됩니다.
//
// 반면 각 매물의 elevationM(해발고도)·riverDistanceM(최근접 하천까지 거리)·river 정보는
// 실제 좌표를 Open-Elevation API(고도)와 OpenStreetMap Overpass API(하천 위치)에 넣어
// 얻은 값입니다. hasFloodHistory·weakDrainage와 hist 항목은 2022.08.08 서울 폭우
// (동작구 신대방동 관측 사상 최고 시간당 141.5mm 등)와 2026.07.09 도림천 침수주의보
// (도시하천유역 침수피해방지대책법 시행 후 첫 발령) 등 공개 보도를 근거로 표시했습니다.
// thr(침수 임계점)은 이 값들로부터 domain/floodScore.js가 계산합니다 — 손으로 써넣은
// 숫자가 아닙니다.

export const REGIONS = [
  {
    id: 'gwanak',
    name: '관악구',
    breadcrumb: ['서울특별시', '관악구'],
    center: [37.4865, 126.9225],
    zoom: 14,
  },
  {
    id: 'dongjak',
    name: '동작구',
    breadcrumb: ['서울특별시', '동작구'],
    center: [37.4955, 126.958],
    zoom: 13,
  },
  {
    id: 'seocho-gangnam',
    name: '강남역 일대',
    breadcrumb: ['서울특별시', '서초구·강남구 (강남역 일대)'],
    center: [37.4935, 127.0205],
    zoom: 14,
  },
  {
    id: 'yeongdeungpo',
    name: '영등포구',
    breadcrumb: ['서울특별시', '영등포구'],
    center: [37.4995, 126.905],
    zoom: 13,
  },
  {
    id: 'guro',
    name: '구로구',
    breadcrumb: ['서울특별시', '구로구'],
    center: [37.5, 126.884],
    zoom: 14,
  },
];

export const DEFAULT_REGION_ID = 'gwanak';

export const LISTINGS = [
  {
    id: 's1',
    region: 'gwanak',
    name: '신림동 도림천변 반지하',
    addr: '관악구 신림동',
    deal: '월세 300 / 38',
    dealType: '월세',
    roomType: '원룸',
    priceValue: 38,
    spec: '원룸 · 17㎡ · B1/3층',
    pval: 38,
    recent: 15,
    photo: '/photos/studio-compact.png',
    lat: 37.485,
    lng: 126.922,
    elevationM: 30,
    riverDistanceM: 179,
    riverName: '도림천',
    banjiha: true,
    hasFloodHistory: true,
    weakDrainage: true,
    hist: [
      { date: '2022.08.08', mm: 136.5, st: 'bad', txt: '반지하 침수 · 인근 사망사고 발생', note: '관악구 신림동 반지하 주택 침수로 일가족 3명 사망 (전국적으로 알려진 사례)' },
      { date: '2026.07.09', mm: null, st: 'bad', txt: '도림천 침수주의보 발령', note: '한강홍수통제소, 도시하천유역법 시행 후 첫 침수주의보 — 신림역 인근 포함' },
    ],
  },
  {
    id: 's2',
    region: 'gwanak',
    name: '신림동 채광좋은 원룸',
    addr: '관악구 신림동',
    deal: '월세 500 / 45',
    dealType: '월세',
    roomType: '원룸',
    priceValue: 45,
    spec: '원룸 · 20㎡ · 3/4층 · 남향',
    pval: 45,
    recent: 14,
    photo: '/photos/kitchen-white.jpg',
    lat: 37.488,
    lng: 126.931,
    elevationM: 28,
    riverDistanceM: 632,
    riverName: '도림천',
    banjiha: false,
    hasFloodHistory: true,
    weakDrainage: true,
    hist: [
      { date: '2022.08.08', mm: 136.5, st: 'bad', txt: '같은 신림동 저지대 반지하 침수 (이 건물은 지상)', note: '동일 폭우 당시 지상 3층인 이 건물은 실질 피해 없음' },
      { date: '2026.07.09', mm: null, st: 'ok', txt: '도림천 침수주의보 구간 (건물 피해 없음)', note: '주의보 발령 구간이나 지상층이라 실제 침수는 없었음' },
    ],
  },
  {
    id: 's3',
    region: 'gwanak',
    name: '신대방역 골목 반지하',
    addr: '관악구 신대방동',
    deal: '월세 800 / 55',
    dealType: '월세',
    roomType: '투룸+',
    priceValue: 55,
    spec: '투룸 · 32㎡ · B1/4층',
    pval: 55,
    recent: 13,
    photo: '/photos/studio-compact.png',
    lat: 37.487595,
    lng: 126.913392,
    elevationM: 26,
    riverDistanceM: 107,
    riverName: '도림천',
    banjiha: true,
    hasFloodHistory: true,
    weakDrainage: true,
    hist: [
      { date: '2022.08.08', mm: 141.5, st: 'bad', txt: '서울 관측 사상 최고 시간당 강수량 기록', note: '인근 신대방동 관측소, 80년 만에 서울 최고 기록(141.5mm/h) 경신' },
      { date: '2026.07.09', mm: null, st: 'bad', txt: '도림천 침수주의보 발령', note: '신대방역 인근이 발령 구간에 명시적으로 포함' },
    ],
  },
  {
    id: 's4',
    region: 'dongjak',
    name: '사당동 언덕 위 빌라',
    addr: '동작구 사당동',
    deal: '전세 2억 4,000',
    dealType: '전세',
    roomType: '투룸+',
    priceValue: 24000,
    spec: '빌라 · 59㎡ · 3/3층 · 언덕',
    pval: 24000,
    recent: 12,
    photo: '/photos/living-bright.jpg',
    lat: 37.479,
    lng: 126.965,
    elevationM: 78,
    riverDistanceM: 2004,
    riverName: '도림천',
    banjiha: false,
    hasFloodHistory: true,
    weakDrainage: false,
    hist: [
      { date: '2022.08.08', mm: 141, st: 'ok', txt: '사당동 시장 침수, 이 지점은 고지대라 피해 없음', note: '동작구 사당동 일대 시장이 성인 가슴높이까지 침수됐으나 해발 78m 지점은 영향 없음' },
    ],
  },
  {
    id: 's5',
    region: 'dongjak',
    name: '사당동 반지하 투룸',
    addr: '동작구 사당동',
    deal: '월세 600 / 48',
    dealType: '월세',
    roomType: '투룸+',
    priceValue: 48,
    spec: '투룸 · 28㎡ · B1/3층',
    pval: 48,
    recent: 11,
    photo: '/photos/studio-compact.png',
    lat: 37.49,
    lng: 126.977,
    elevationM: 52,
    riverDistanceM: 1289,
    riverName: '반포천',
    banjiha: true,
    hasFloodHistory: true,
    weakDrainage: false,
    hist: [
      { date: '2022.08.08', mm: 141, st: 'bad', txt: '사당시장 침수 (성인 가슴높이)', note: '동작구 사당동 시장 일대 성인 가슴높이까지 침수' },
    ],
  },
  {
    id: 's6',
    region: 'dongjak',
    name: '노량진 학원가 원룸',
    addr: '동작구 노량진동',
    deal: '월세 400 / 42',
    dealType: '월세',
    roomType: '원룸',
    priceValue: 42,
    spec: '원룸 · 16㎡ · 2/5층',
    pval: 42,
    recent: 10,
    photo: '/photos/room-shelf.jpg',
    lat: 37.51101,
    lng: 126.941463,
    elevationM: 23,
    riverDistanceM: 1319,
    riverName: '한강',
    banjiha: false,
    hasFloodHistory: false,
    weakDrainage: false,
    hist: [
      { date: '전 기간', mm: null, st: 'ok', txt: '확인된 침수 이력 없음', note: '한강 인접 저지대이나 공개된 침수 피해 보고는 없음' },
    ],
  },
  {
    id: 's7',
    region: 'seocho-gangnam',
    name: '강남역 초역세권 오피스텔',
    addr: '서초구 서초동',
    deal: '전세 2억 9,000',
    dealType: '전세',
    roomType: '오피스텔',
    priceValue: 29000,
    spec: '오피스텔 · 33㎡ · 12/20층',
    pval: 29000,
    recent: 9,
    photo: '/photos/living-spacious.jpg',
    lat: 37.497556,
    lng: 127.026808,
    elevationM: 24,
    riverDistanceM: 170,
    riverName: '반포천',
    banjiha: false,
    hasFloodHistory: true,
    weakDrainage: true,
    hist: [
      { date: '2022.08.08', mm: 141, st: 'bad', txt: '강남역 일대 도로·지하상가 침수', note: '항아리 지형으로 도로가 강처럼 변함, 차량 다수 침수·고립' },
      { date: '2010~2022 반복', mm: null, st: 'bad', txt: '상습 침수 구역 (10여 년간 반복)', note: '반포천 상류부 통수능력 부족 등으로 2010·2011·2022년 반복 침수, 서울시가 대심도 배수터널 공사 중(2027년 완공 목표)' },
    ],
  },
  {
    id: 's8',
    region: 'seocho-gangnam',
    name: '서초동 반지하 투룸',
    addr: '서초구 서초동',
    deal: '월세 700 / 60',
    dealType: '월세',
    roomType: '투룸+',
    priceValue: 60,
    spec: '투룸 · 30㎡ · B1/4층',
    pval: 60,
    recent: 8,
    photo: '/photos/studio-compact.png',
    lat: 37.485,
    lng: 127.01,
    elevationM: 39,
    riverDistanceM: 960,
    riverName: '반포천',
    banjiha: true,
    hasFloodHistory: true,
    weakDrainage: true,
    hist: [
      { date: '2022.08.08', mm: 141, st: 'bad', txt: '강남역 인근 저지대 침수 영향권', note: '서초동 일대, 강남역과 동일한 폭우 영향권으로 침수 보고' },
    ],
  },
  {
    id: 's9',
    region: 'seocho-gangnam',
    name: '역삼동 강남역 오피스텔',
    addr: '강남구 역삼동',
    deal: '전세 3억 2,000',
    dealType: '전세',
    roomType: '오피스텔',
    priceValue: 32000,
    spec: '오피스텔 · 29㎡ · 15/25층',
    pval: 32000,
    recent: 7,
    photo: '/photos/complex-exterior.jpg',
    lat: 37.50023,
    lng: 127.026805,
    elevationM: 33,
    riverDistanceM: 134,
    riverName: '반포천',
    banjiha: false,
    hasFloodHistory: true,
    weakDrainage: true,
    hist: [
      { date: '2022.08.08', mm: 141, st: 'bad', txt: '강남역 인근 침수 영향권', note: '역삼동 강남대로 변, 강남역 침수와 동일 생활권' },
    ],
  },
  {
    id: 's10',
    region: 'yeongdeungpo',
    name: '대림동 하천변 반지하',
    addr: '영등포구 대림동',
    deal: '월세 350 / 32',
    dealType: '월세',
    roomType: '원룸',
    priceValue: 32,
    spec: '원룸 · 15㎡ · B1/2층',
    pval: 32,
    recent: 6,
    photo: '/photos/studio-compact.png',
    lat: 37.488,
    lng: 126.896,
    elevationM: 19,
    riverDistanceM: 96,
    riverName: '도림천',
    banjiha: true,
    hasFloodHistory: true,
    weakDrainage: true,
    hist: [
      { date: '2022.08.08', mm: null, st: 'bad', txt: '대림동 일대 부분 침수', note: '영등포구 대림어린이공원 등 인근 부분 침수 확인' },
      { date: '2026.07.09', mm: null, st: 'bad', txt: '도림천 침수주의보 발령 (하천 바로 인접)', note: '하천에서 100m 이내로 주의보 발령 시 가장 먼저 영향권' },
    ],
  },
  {
    id: 's11',
    region: 'yeongdeungpo',
    name: '대림동 골목 투룸',
    addr: '영등포구 대림동',
    deal: '월세 600 / 50',
    dealType: '월세',
    roomType: '투룸+',
    priceValue: 50,
    spec: '투룸 · 34㎡ · 3/4층',
    pval: 50,
    recent: 5,
    photo: '/photos/bedroom-cozy.jpg',
    lat: 37.504,
    lng: 126.905,
    elevationM: 18,
    riverDistanceM: 1022,
    riverName: '도림천',
    banjiha: false,
    hasFloodHistory: true,
    weakDrainage: true,
    hist: [
      { date: '2022.08.08', mm: null, st: 'bad', txt: '대림동 일대 부분 침수', note: '영등포구 대림어린이공원 등 인근 부분 침수 확인' },
      { date: '2026.07.09', mm: null, st: 'ok', txt: '도림천 침수주의보 구간 (건물 피해 없음)', note: '하천에서 다소 떨어져 있어 2026년 주의보 당시 피해 없음' },
    ],
  },
  {
    id: 's12',
    region: 'yeongdeungpo',
    name: '신길동 반지하 원룸',
    addr: '영등포구 신길동',
    deal: '월세 400 / 40',
    dealType: '월세',
    roomType: '원룸',
    priceValue: 40,
    spec: '원룸 · 18㎡ · B1/3층',
    pval: 40,
    recent: 4,
    photo: '/photos/studio-compact.png',
    lat: 37.506521,
    lng: 126.911911,
    elevationM: 29,
    riverDistanceM: 1615,
    riverName: '도림천',
    banjiha: true,
    hasFloodHistory: true,
    weakDrainage: false,
    hist: [
      { date: '2022.08.08', mm: null, st: 'bad', txt: '신길동 서울대방초 일대 부분 침수', note: '영등포구 신길동 일부 저지대 침수 확인' },
    ],
  },
  {
    id: 's13',
    region: 'guro',
    name: '구로동 안양천뷰 빌라',
    addr: '구로구 구로동',
    deal: '전세 1억 8,000',
    dealType: '전세',
    roomType: '투룸+',
    priceValue: 18000,
    spec: '빌라 · 42㎡ · 2/3층',
    pval: 18000,
    recent: 3,
    photo: '/photos/lounge-common.jpg',
    lat: 37.488,
    lng: 126.879,
    elevationM: 15,
    riverDistanceM: 695,
    riverName: '안양천',
    banjiha: false,
    hasFloodHistory: false,
    weakDrainage: true,
    hist: [
      { date: '2026.07.09', mm: null, st: 'ok', txt: '안양천 침수주의보 구간 (피해 없음)', note: '주의보 대상 하천 목록에 포함되나 실제 피해 보고는 없음' },
    ],
  },
  {
    id: 's14',
    region: 'guro',
    name: '구로동 반지하 투룸',
    addr: '구로구 구로동',
    deal: '월세 550 / 45',
    dealType: '월세',
    roomType: '투룸+',
    priceValue: 45,
    spec: '투룸 · 27㎡ · B1/4층',
    pval: 45,
    recent: 2,
    photo: '/photos/studio-compact.png',
    lat: 37.501,
    lng: 126.89,
    elevationM: 20,
    riverDistanceM: 265,
    riverName: '도림천',
    banjiha: true,
    hasFloodHistory: false,
    weakDrainage: true,
    hist: [
      { date: '2026.07.09', mm: null, st: 'bad', txt: '도림천 침수주의보 발령 구간', note: '도림천에서 265m 지점 — 주의보 발령 구간에 포함' },
    ],
  },
  {
    id: 's15',
    region: 'guro',
    name: '신도림역 오피스텔',
    addr: '구로구 신도림동',
    deal: '전세 2억 2,000',
    dealType: '전세',
    roomType: '오피스텔',
    priceValue: 22000,
    spec: '오피스텔 · 31㎡ · 18/22층',
    pval: 22000,
    recent: 1,
    photo: '/photos/living-spacious.jpg',
    lat: 37.51057,
    lng: 126.88316,
    elevationM: 22,
    riverDistanceM: 428,
    riverName: '도림천',
    banjiha: false,
    hasFloodHistory: false,
    weakDrainage: true,
    hist: [
      { date: '2026.07.09', mm: null, st: 'ok', txt: '도림천 침수주의보 구간 (피해 없음)', note: '주의보 발령 구간이나 실제 침수 피해는 없음' },
    ],
  },
];
